#!/usr/bin/env python3

import os
import sys

PSTATE_ROOT = "/sys/devices/system/cpu/intel_pstate/"
MAP = {
    "max": "max_perf_pct",
    "min": "min_perf_pct",
    "turbo": "no_turbo",
}

STATES = {
    "powersave": {
        "min": "24",
        "max": "30",
        "turbo": "0",
    },
    "balanced": {
        "min": "24",
        "max": "75",
        "turbo": "1",
    },
    "standard": {
        "min": "24",
        "max": "100",
        "turbo": "1",
    },
    "max": {
        "min": "100",
        "max": "100",
        "turbo": "1",
    },
}


def change_state(state):
    for key in state:
        fpath = os.path.join(PSTATE_ROOT, MAP[key])
        with open(fpath, 'w') as fd:
            fd.write(state[key])


def main(state=None):
    if state is None:
        for k, v in MAP.items():
            fpath = os.path.join(PSTATE_ROOT, v)
            with open(fpath, 'r') as fd:
                value = fd.read().strip()
            if k == 'turbo':
                print(k, "false" if value == "0" else "true")
                continue
            print(k, value)
        return 0

    change_state(STATES[state])
    return 0



if __name__ == "__main__":
    sys.exit(main(*sys.argv[1:]))
